chore: updated to synapse v1.148.0

diff --git a/docker/Dockerfile b/docker/Dockerfile
--- a/docker/Dockerfile
+++ b/docker/Dockerfile
@@ -1,4 +1,4 @@
-FROM matrixdotorg/synapse:v1.98.0
+FROM matrixdotorg/synapse:v1.148.0
 LABEL maintainer="AirGap Team <hi@airgap.it>"
 
 # RUN apk add libsodium-dev gcc
@@ -8,7 +8,7 @@ RUN pip install psycopg2 pysodium
 
 RUN mkdir -p /keys
 
-COPY crypto_auth_provider.py /usr/local/lib/python3.11/site-packages/
+COPY crypto_auth_provider.py /usr/local/lib/python3.13/site-packages/
 COPY homeserver.yaml /config/
 COPY synapse.log.config /config/
 COPY synapse_master.service /etc/systemd/system/
@@ -16,10 +16,14 @@ COPY synapse_worker@.service /etc/systemd/system/
 COPY matrix_synapse.target /etc/systemd/system/
 COPY workers /config/workers
 COPY shared_config.yaml /config/
-COPY beacon_info_module.py /usr/local/lib/python3.11/site-packages/
+COPY beacon_info_module.py /usr/local/lib/python3.13/site-packages/
 
-# run change on max size
-RUN sed -i 's/65536/1048576/' /usr/local/lib/python3.11/site-packages/synapse/api/constants.py
+# Increase max event size (1MB instead of default 64KB).
+# Beacon messages can exceed the default Matrix PDU size limit.
+# Runs before COPY so code changes don't invalidate this layer.
+RUN sed -i 's/^MAX_PDU_SIZE = 65536$/MAX_PDU_SIZE = 1048576/' /usr/local/lib/python3.13/site-packages/synapse/api/constants.py && \
+    grep -q '^MAX_PDU_SIZE = 1048576$' /usr/local/lib/python3.13/site-packages/synapse/api/constants.py || \
+    (echo "FATAL: PDU size patch failed - 'MAX_PDU_SIZE = 65536' not found in constants.py. Upstream may have changed." >&2 && exit 1)
 
 COPY wait-for.sh /usr/local/bin/
 COPY synctl_entrypoint.sh /usr/local/bin/
